### ISSUE TITLE
app_rv = app(environ, start_response) TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by younesidsouguou** [lgsvl/second-ros#2]
At the section of "How to Train SECOND Network", subsection "Data Visualization", Step 7 click "Load" I come across the following exceptions:

127.0.0.1 - - [29/Aug/2019 09:34:11] "OPTIONS /api/readinfo HTTP/1.1" 200 -
ERROR: your root path is incorrect.
[2019-08-29 09:34:11,552] ERROR in app: Exception on /api/readinfo [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1993, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1835, in full_dispatch_request
    return self.finalize_request(rv)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1850, in finalize_request
    response = self.make_response(rv)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2001, in make_response
    reraise(TypeError, new_error, sys.exc_info()[2])
  File "/usr/local/lib/python3.6/dist-packages/flask/_compat.py", line 35, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1993, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/wrappers/base_response.py", line 26, in _run_wsgi_app
    return _run_wsgi_app(*args)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/test.py", line 1119, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a dict.
127.0.0.1 - - [29/Aug/2019 09:34:11] "POST /api/readinfo HTTP/1.1" 500 -

Any enlightenment ?

**Comment by daviduhm** [comment]
Have you collected your data before trying to visualize data? Data visualization is there to visualize your collected data before training a model. Please confirm that your *infoPath* from the visualization tool and make sure that you actually have a pickle file for your collected data in your *infoPath* (e.g., /root/data/kitti/training/kitti_infos_train.pkl).

[Here](https://github.com/lgsvl/second-ros#how-to-collect-data) is the documentation for collecting data, and if you'd like to visualize the provided [sample data](https://github.com/lgsvl/second-ros/tree/master/data/kitti) you can skip the first part and do the [Preprocessing Data](https://github.com/lgsvl/second-ros#preprocessing-data) part to generate pickles as follows: `python second.pytorch/second/create_data.py create_kitti_info_file --data_path=/root/data/kitti`
